% calculates task-related, baseline-correctd coherence using wavelets

function ...
    [Coh_mean,...
    Coh_trial_amp,...
    Coh_trial_phase,...
    CohF,...
    Coh_baseline,...
    Coh_baseline_mean]=...                                
    make_Coh_using_MATLAB_wcoherence(...
    signal1,...
    signal2,...
    event_indices,...
    start_epoch_at_this_sample_point,...
    stop_epoch_at_this_sample_point,...
    start_baseline_indices,...
    stop_baseline_indices,...
    skip,...
    Fs)



number_of_sample_points_in_signal=size(signal1,2);
number_of_surrogate_runs=size(skip,2);

event_indices(find(event_indices<...                        %take out ones too close to the end or the begining
    abs(start_epoch_at_this_sample_point)))=[];
event_indices(find(event_indices>...
    number_of_sample_points_in_signal-...
    abs(stop_epoch_at_this_sample_point)))=[];
number_of_epochs=length(event_indices);
number_of_sample_points_in_epoch=...
    length(...
    start_epoch_at_this_sample_point:...
    stop_epoch_at_this_sample_point);
number_of_sample_points_in_baseline=length(start_baseline_indices(1):...
    stop_baseline_indices(1));



[Coh(:,:),Cxy,CohF]=wcoherence(signal1,signal2,Fs);

for e=1:number_of_epochs
    Coh_trial_amp(:,:,e)=Coh(:,event_indices(e)+(start_epoch_at_this_sample_point:stop_epoch_at_this_sample_point));
    Coh_trial_phase(:,:,e)=angle(Cxy(:,event_indices(e)+(start_epoch_at_this_sample_point:stop_epoch_at_this_sample_point)));

    Coh_baseline(:,:,e)=Coh(:,event_indices(e)+(round(start_baseline_indices(e)):round(stop_baseline_indices(e))));
    
    Coh_baseline_mean(:,e)=squeeze(mean(Coh_baseline(:,:,e),2));
    
    Coh_trial_amp(:,:,e)=Coh_trial_amp(:,:,e)-repmat(Coh_baseline_mean(:,e),1,size(Coh_trial_amp,2));
end


Coh_mean=squeeze(mean(Coh_trial_amp,3));


