function ...
    [epoch_time,...
    start_epoch_at_this_sample_point,...
    stop_epoch_at_this_sample_point,...
    start_baseline_at_this_sample_point,...
    stop_baseline_at_this_sample_point,...
    number_of_sample_points_in_epoch]=...
    make_epoch_time(...
    start_epoch_at_this_time,...
    stop_epoch_at_this_time,...
    start_baseline_at_this_time,...
    stop_baseline_at_this_time,...
    sampling_rate)

%generates a vector which gives a ms value for each sample pt in epoch.

start_epoch_at_this_sample_point=fix(sampling_rate*start_epoch_at_this_time/1000); % converts time to sampling points
stop_epoch_at_this_sample_point=fix(sampling_rate*stop_epoch_at_this_time/1000);
start_baseline_at_this_sample_point=fix(sampling_rate*start_baseline_at_this_time/1000); % converts time to sampling points
stop_baseline_at_this_sample_point=fix(sampling_rate*stop_baseline_at_this_time/1000);
number_of_sample_points_in_epoch=length(start_epoch_at_this_sample_point:stop_epoch_at_this_sample_point);
epoch_time=1000*(start_epoch_at_this_sample_point:stop_epoch_at_this_sample_point)/sampling_rate;
